export const GET_DATA = "GET_DATA";
export const ADD_AMOUNT_PRODUCT = "ADD_AMOUNT_PRODUCT";
export const MINUS_AMOUNT_PRODUCT = "MINUS_AMOUNT_PRODUCT";
export const REMOVE_PRODUCT = "REMOVE_PRODUCT";
